services:
  ravendb:
    image: ravendb/ravendb:ubuntu-latest
    container_name: ravendb
    ports:
      - "8080:8080"
      - "38888:38888"
    restart: unless-stopped
    environment:
      - RAVEN_Setup_Mode=None
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
    volumes:
      - ravendb_data:/var/lib/ravendb/data
    networks:
      - ravendb_network

  api:
    build:
      dockerfile: Dockerfile.api
      context: .
    container_name: api
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - ravendb_network

volumes:
  ravendb_data:

networks:
  ravendb_network:
    driver: bridge