services:
  tppe-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: tppe-api
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      - ravendb_network

  tppe-api-test:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: tppe-api-test
    command: make ruff && make test
    networks:
      - ravendb_network

  tppe-front:
    build:
      context: .
      dockerfile: Dockerfile.front
    container_name: tppe-front
    ports:
      - "3000:3000"  # porta padrão do Next.js
    restart: unless-stopped
    networks:
      - ravendb_network
    depends_on:
      - tppe-api

volumes:
  ravendb_data:

networks:
  ravendb_network:
    driver: bridge
