[project]
name = "tppe"
version = "0.1.0"
description = "Projeto da Disciplina de TPPE da Universidade de Brasília"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "httpx>=0.28.1",
    "pydantic>=2.11.4",
    "pytest>=8.3.5",
    "uvicorn>=0.34.2",
]
