name: CI

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    container:
      image: rafaelnobre00/idea-analytics-ci:latest
      options: --user root  # if you need root for installs; otherwise omit
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies
        run: |
          git submodule update --init
          make install-dependencies

      - name: Lint with Ruff
        run: make ruff

      - name: Run tests
        run: |
          cp .env.example .env
          mkdir -p api/static/ui5
          make test
