name: CI

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    container:
      image: rafaelnobre00/tppe-ci:latest
      options: --user root
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies
        run: |
          uv sync

      - name: Lint with Ruff
        run: make ruff

      - name: Run tests
        run: |
          cp .env.example .env
          dotnet /__w/tppe-project/tppe-project/.venv/lib/python3.13/site-packages/ravendb_embedded/target/nuget/contentFiles/any/any/RavenDBServer/Raven.Server.dll --Embedded.ParentProcessId=421 --License.Eula.Accepted=true --Setup.Mode=None --DataDir=/__w/tppe-project/tppe-project/.venv/lib/python3.13/site-packages/ravendb_embedded/RavenDB --Logs.Path=/__w/tppe-project/tppe-project/.venv/lib/python3.13/site-packages/ravendb_embedded/RavenDB/Logs --ServerUrl=http://127.0.0.1:0
